plugins:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      extensions:
      - .js
      - .vue
  eslint:
    enabled: true
    config:
      languages:
      - javascript
      extensions:
      - .js
      - .vue
