engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      extensions:
      - .js
      - .vue
eslint:
  enabled: true
  config:
    extensions:
    - .js
    - .vue
ratings:
   paths:
   - "**.js"
   - "**.vue"
