swagger: '2.0'
info:
  title: 'BBAI Scan Server API'
  version: '0.1'
  description: 'This is scan control server run on BBAI with Flask'
paths:
  /config:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              accessToken: f58ba22059f5a8aa8f346e0f40987adab326041fac99029c909bef2c6300821a
          schema:
            type: object
            properties:
              accessToken:
                type: string
                description: アクセストークン
            required:
              - accessToken
      summary: Scan Configuration
      operationId: Scan Configuration
      description: |-
        #### About

        * configure scan settings
      tags:
        - Polymerization
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              pinConfigs:
                type: array
                items: 
                  type: number
              size:
                type: number
                description: length of scan square u32sm[0]
              speed:
                type: number
                description: send pulse every X millisecond u32sm[1]
              shape:
                type: number
                description: '0: E shape 1: F shape u32sm[2]'
              invert:
                type: number
                description: '0:not inverted pulse 1: inverted pulse u32sm[3]'
            required:
              - pinConfigs
              - size
              - speed
              - shape
              - invert
            example:
              pinConfigs:
                - name: pinName
                  value: 0
              size: 1000
              speed: 1
              shape: 0
              invert: 1
      produces:
        - application/json
  /configXY:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              accessToken: f58ba22059f5a8aa8f346e0f40987adab326041fac99029c909bef2c6300821a
          schema:
            type: object
            properties:
              accessToken:
                type: string
                description: アクセストークン
            required:
              - accessToken
      summary: Scan Configuration
      operationId: XYScan Configuration
      description: |-
        #### About

        * configure scan settings
      tags:
        - Polymerization
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              pinConfigs:
                type: array
                items: 
                  type: number
              invert:
                type: number
                description: '0:not inverted pulse 1: inverted pulse u32sm[3]'
              widthGo:
                type: number
                description: length of scan square u32sm[4]
              widthCome:
                type: number
                description: send pulse every X millisecond u32sm[5]
              heightGo:
                type: number
                description: '0: E shape 1: F shape u32sm[6]'
              heightCome:
                type: number
                description: '0: E shape 1: F shape u32sm[7]'
              repeatNum:
                type: number
                description: '-1: infinite, >1: finite u32sm[8]'
            required:
              - pinConfigs
              - widthGo
              - widthCome
              - heightGo
              - heightCome
              - invert
              - repeatNum
            example:
              pinConfigs:
                - name: pinName
                  value: 0
              invert: 1
              widthGo: 100
              widthCome: 2
              heightGo: 100
              heightCome: 2
              repeatNum: 10
      produces:
        - application/json
tags:
  - name: Polymerization
