version: "2"
services:
  swagger:
    image: swaggerapi/swagger-ui:v3.33.0
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi
    environment:
      API_URL: openapi/2pAPI.v1.yaml
    ports:
      - "8050:8080"
