# unzip ~/Downloads/abu-gh-pages.zip -d .
version: '3.1'
services:
  web:
    image: nginx:1.15.11-alpine
    ports:
      - "61990:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../dist/abu-gh-pages:/var/www/html/abu
    restart: always
