swagger: '2.0'
info:
  title: ''
  version: ''
  description: ''
paths:
  /config:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/json:
              accessToken: f58ba22059f5a8aa8f346e0f40987adab326041fac99029c909bef2c6300821a
          schema:
            type: object
            properties:
              accessToken:
                type: string
                description: アクセストークン
            required:
              - accessToken
      summary: Scan Configuration
      operationId: Scan Configuration
      description: |-
        #### About

        * configure scan settings
      tags:
        - Polymerization
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              pinConfigs:
                type: array
              size:
                type: number
                description: length of scan square u32sm
              speed:
                type: number
                description: send pulse every X millisecond u32sm
              shape:
                type: number
                description: '0: E shape 1: F shape u32sm'
              invert:
                type: number
                description: '0:not inverted pulse 1: inverted pulse u32sm'
            required:
              - pinConfigs
              - size
              - speed
              - shape
              - invert
            example:
              pinConfigs:
                - name: pinName
                  value: 0
              size: 1000
              speed: 1
              shape: 0
              invert: 1
      produces:
        - application/json
definitions:
  Endpoint: {}
securityDefinitions: {}
tags:
  - name: Polymerization
